### ISSUE TITLE
使用Rapidjson的时候遇到了一点问题

### ISSUE THREAD

**Issue by w1ng** [chexiongsheng/build_xlua_with_libs#1]
如题,当服务端发送的json字符串中有null字段时,null会被解析成一个lua function...
例如:
`{"a":{},"b":null}`
这样的一个json数组,取`b`的时候会得到一个function,而不是nil,
虽然能尽量通过规范来约束服务端尽量不发null过来,但是还是希望从代码层面就能杜绝这种情况的产生,
请问这里可以修改一下吗?
或者简单讲一下libs的编译过程,我去尝试修改一下代码

**Comment by chexiongsheng** [comment]
我看了下，这是这个rapidjson binding的设定：null用一个特定函数来代表
你可以通过这样来判断是不是null
print(t.b == rapidjson.null)

ps，个人觉得这也合理，比如一个数组，如果中间是一个nil的话，数组就被截断了，#取长度只取到nil那

**Comment by w1ng** [comment]
好的,理解了.
我重新封装一个方法来判断是否为nil好了,类似这样:
`function isNull(obj)
    if not json then
        json = require 'rapidjson'
    end
    if not obj or obj == json.null then
        return true
    end
    return false
end`
