### ISSUE TITLE
问题Plugins colliding with each other.

### ISSUE THREAD

**Issue by tanhaojin** [chexiongsheng/build_xlua_with_libs#16]
Plugin 'libxlua.so' is used from several locations:
 Assets/Plugins/x86/libxlua.so would be copied to <PluginPath>/libxlua.so
 Assets/Plugins/x86_64/libxlua.so would be copied to <PluginPath>/libxlua.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()

使用更新的插件，在build时报了上边的错误
请问大佬有什么解决方法吗？谢谢

**Comment by chexiongsheng** [comment]
可能你漏更新meta，或者不同版本unity的meta文件不兼容。
或者你手动设置下平台可以解决，Assets/Plugins/x86/libxlua.so 设置为linux standalone 32位，Assets/Plugins/x86_64/libxlua.so 设置linux standalone 64位

**Comment by tanhaojin** [comment]
设置后可以buid了 ，非常感谢
