### ISSUE TITLE
关于libs中的模块 和 CustomLoader 的使用问题

### ISSUE THREAD

**Issue by midGitub** [chexiongsheng/build_xlua_with_libs#19]
增加了 CustomLoader 后 require 'protoc' 会报错，暂时的解决方法是在 增加 CustomLoader 之前 先 require 这些模块。想问问车前辈还有别的推荐做法么。

**Comment by chexiongsheng** [comment]
那是因为你的CustomLoader写得有问题，仔细看并理解文档

**Comment by midGitub** [comment]
多谢回复 找到问题了。如果按照指定方式去查找的，但是又没找到的话。 应该返回null。现在表现正常了。
