### ISSUE TITLE
请问支持vs2013编译嘛?

### ISSUE THREAD

**Issue by daaoling** [chexiongsheng/build_xlua_with_libs#2]
请问支持vs2013编译嘛?
![image](https://cloud.githubusercontent.com/assets/11972308/25314038/6206124c-286e-11e7-8585-fe124e140ba6.png)
我就改了下编译版本 然后一运行就不对了

**Comment by chexiongsheng** [comment]
我没2013环境，你自行定位下，不行就安装2015

**Comment by daaoling** [comment]
恩 好的

2017-04-24 9:45 GMT+08:00 chexiongsheng <notifications@github.com>:
