### ISSUE TITLE
使用pbc报错。

### ISSUE THREAD

**Issue by jj391** [chexiongsheng/build_xlua_with_libs#22]
EntryPointNotFoundException: luaopen_protobuf_c
XLua.LuaDLL.Lua.LoadProtobufC (IntPtr L) (at Assets/BuildInInit.cs:49)
(wrapper native-to-managed) XLua.LuaDLL.Lua:LoadProtobufC (intptr)
XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:270)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:290)
Helloworld.Start () (at Assets/Helloworld/Helloworld.cs:32)

**Comment by chexiongsheng** [comment]
默认不支持pbc，pbc要自己编译，看首页
