### ISSUE TITLE
你好 xlua帮忙编译个android平台

### ISSUE THREAD

**Issue by cuijingzhen** [chexiongsheng/build_xlua_with_libs#24]
xlua帮忙编译个android平台带有pbc的吧，弄了好久android弄不好  只弄了ios、mac、windows平台带有pbc的  谢谢

**Comment by chexiongsheng** [comment]
你在window编译android？
mac或者linux下，下载android-ndk-r10e到用户目录，执行make_android_lua53.sh，极其简单。

**Comment by chexiongsheng** [comment]
另外，默认不是pbc，而是lua-protobuf，如果你非要用pbc（已经不维护），按首页操作下

**Comment by chexiongsheng** [comment]
如果是lua-protobuf，本来就编译好了，在plugin_XXX目录

**Comment by cuijingzhen** [comment]
我下载了android-ndk-r10e到用户目录，执行make_android_lua53.sh ，但是报错。能麻烦告诉下这么解决吗
CMake Error at cmake/android.toolchain.cmake:616 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:16 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:
cp: build_v7a/libxlua.so: No such file or directory
CMake Error at cmake/android.toolchain.cmake:616 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:16 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:
cp: build_x86/libxlua.so: No such file or directory

**Comment by cuijingzhen** [comment]
我是用的mac

**Comment by chexiongsheng** [comment]
感觉你没放对位置，执行：
ls ~/android-ndk-r10e/
看看有东西么
没有就移动过去，或者设置ANDROID_NDK环境变量指向你的目录

**Comment by cuijingzhen** [comment]
突然就可以编译了。。。我把ndk删掉重新放到用户路径下就好了。。。谢谢哈

**Comment by cuijingzhen** [comment]
但是android加pbc是在哪加 -DPBC=ON 这个呢  我看例子是在-G前面加  但是我看android里面没-G

**Comment by chexiongsheng** [comment]
cmake之后就可以

**Comment by cuijingzhen** [comment]
好的谢谢

**Comment by cuijingzhen** [comment]
ok了  万分感谢

**Comment by lvchy** [comment]
你好，我在mac 下编译 安卓 会报错 ：CMake Error at cmake/android.toolchain.cmake:739 (message):
  Specified toolchain "arm-linux-androideabi-clang3.6" is missing in your NDK
  or broken.  Please verify that your NDK is working or select another
  compiler toolchain.

win，ios，macos 都ok了。
安卓版本不能用mac编译 一定要linux吗。。

非常感谢～
