### ISSUE TITLE
关于支持android arm64

### ISSUE THREAD

**Issue by yangchg** [chexiongsheng/build_xlua_with_libs#26]
请问可以提供android arm64库么，谢谢。

**Comment by Winvz** [comment]
同需要

**Comment by chexiongsheng** [comment]
已经提供
lua53：https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/build/plugin_lua53
luajit：https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/build/plugin_luajit

**Comment by yangchg** [comment]
thank you!
