### ISSUE TITLE
大大更新下，自己总是编译不出来

### ISSUE THREAD

**Issue by Winvz** [chexiongsheng/build_xlua_with_libs#27]

**Comment by Winvz** [comment]
CMake Error: The source directory "/Users/wanbei" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
cp: build_v7a/libxlua.so: No such file or directory
CMake Error: The source directory "/Users/wanbei" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
cp: build_x86/libxlua.so: No such file or directory
我在Mac下执行sh文件报错，这是环境问题么

**Comment by Winvz** [comment]
wanbeideMac-mini:build wanbei$ /Users/wanbei/build/make_android_lua53.sh 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ANDROID_ABI
    ANDROID_TOOLCHAIN_NAME


-- Build files have been written to: /Users/wanbei/build
Error: could not load cache
cp: build_v7a/libxlua.so: No such file or directory
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ANDROID_ABI
    ANDROID_TOOLCHAIN_NAME


-- Build files have been written to: /Users/wanbei/build
Error: could not load cache
cp: build_x86/libxlua.so: No such file or directory

**Comment by chexiongsheng** [comment]
https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/build这不是有编译好的么？

**Comment by Winvz** [comment]
你这个支持到2018.2.20，项目用的是2018.4.0

**Comment by chexiongsheng** [comment]
所有unity版本都通用的吧

**Comment by chexiongsheng** [comment]
lua53：https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/build/plugin_lua53/Plugins
luajit：https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/build/plugin_luajit/Plugins
