### ISSUE TITLE
安卓编译失败

### ISSUE THREAD

**Issue by lvchy** [chexiongsheng/build_xlua_with_libs#30]
你好，因为项目要用pbc，所以重新编译了xlua。
但是在mac 下编译 安卓 会报错 ：CMake Error at cmake/android.toolchain.cmake:739 (message):
Specified toolchain "arm-linux-androideabi-clang3.6" is missing in your NDK
or broken. Please verify that your NDK is working or select another
compiler toolchain.

win，ios，macos 都ok了。
安卓版本不能用mac编译 一定要linux吗。。

ndk 是 r10e.
使用都是 lua53 系列

非常感谢～

**Comment by chexiongsheng** [comment]
我自己是在linux编译
mac下很多人试过也可以。
