### ISSUE TITLE
About compile option PBC

### ISSUE THREAD

**Issue by OscarKen** [chexiongsheng/build_xlua_with_libs#31]
-DPBC=ON
should be
 -D PBC=ON

**Comment by OscarKen** [comment]
build_xlua_with_libs/build/CMakeLists.txt line 51
if (NOT PBC)
should be
if (PBC)
?

**Comment by chexiongsheng** [comment]
CMakeLists.txt no problom.

two protobuf lib supported, default is lua-protobuf, you can select pbc by setting the flag -DPBC=ON.
pbc is no longer maintained, so not recommended.

**Comment by OscarKen** [comment]
OK, great job!
Thanks very much!
