### ISSUE TITLE
issues webgl

### ISSUE THREAD

**Issue by doomixi** [chexiongsheng/build_xlua_with_libs#32]
![image](https://user-images.githubusercontent.com/45234215/74497860-52c67e80-4f11-11ea-8450-ee9f9af85f7e.png)

**Comment by chengyimingvb** [comment]
我也遇到了这个错误，请问现在解决了吗？

**Comment by chengyimingvb** [comment]
我也遇到了这个错误，请问现在解决了吗？ @doomixi

**Comment by chexiongsheng** [comment]
原因是库没加到webgl编译里头。
把相应的代码和xlua源码做类似的处理即可
