### ISSUE TITLE
关于Plugins下x86和x86_64的so文件

### ISSUE THREAD

**Issue by JammeLee** [chexiongsheng/build_xlua_with_libs#33]
关于Plugins下x86和x86_64文件夹中的libxlua.so文件，有两个问题想请教一下：
- 做什么用的
- 如何编译才能得到呢

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;一直以为x86和x86_64文件夹是放PC下的dll文件的，所以很费解为什么会有so文件呢。

**Comment by chexiongsheng** [comment]
linux用的

**Comment by JammeLee** [comment]
好的，明白了，感谢大佬。
