### ISSUE TITLE
更新了一下最新版本的xlua,版本号对不上了

### ISSUE THREAD

**Issue by w1ng** [chexiongsheng/build_xlua_with_libs#4]
如题,xlua_get_lib_version()返回的版本号(100)和xlua当前的版本(101)对不上.
建议readme里面加个编译说明...
如果使用的xlua文件,能直接从xlua的仓库里引用最新的,就更好了...

**Comment by Think-Jumper** [comment]
我发现我编译后的c，在获取版本的时候跟C#代码里面的版本对不上号，但是我检查了c语言一遍又一遍，是104没错的，但是Android机子上不知道为啥老是获取到103

**Comment by chexiongsheng** [comment]
@Think-Jumper 编译出错，或者是编译后没拷贝到plugins下吧

**Comment by Think-Jumper** [comment]
最后检查了，是编译生成的缓存文件清空有问题，由于是人手动删掉旧版生成的编译工程，情况不熟悉导致清的文件不对，留了些旧导致有问题。建议作者如果顺便就写个类似clear的脚本命令附带发布，降低下普罗大众的低错误成本。
