### ISSUE TITLE
make_ios_luajit.sh 执行需要密码

### ISSUE THREAD

**Issue by Naiheya** [chexiongsheng/build_xlua_with_libs#42]
请问一下make_ios_luajit.sh 在mac上执行需要密码 这个密码是什么密码呢？mac开机密码试过也不行

**Comment by chexiongsheng** [comment]
当前用户的密码，没有的话直接回车

**Comment by Naiheya** [comment]
你好 我这边mac并没有登录appleID 我直接回车但是密码还是错误，这个用户是具体指的什么用户呢
<img width="1255" alt="QQ图片20210926104135" src="https://user-images.githubusercontent.com/46367944/134791473-a4029b1b-c4b5-41e4-bf85-c1c325723372.png">
？

**Comment by chexiongsheng** [comment]
不是appid。。
等同于sudo，明白？

**Comment by Naiheya** [comment]
好的，谢谢，不知道为什么没设置密码就不行，我设置了一个密码后就可以了
