### ISSUE TITLE
Lua exception : error loading module xxx from CustomLoader, xxx.lua:1: unexpected symbol near '<\239>

### ISSUE THREAD

**Issue by 751500365** [chexiongsheng/build_xlua_with_libs#48]
unity 2020 用的是plugins 目录下libs ，请问如何解决，看到网上有文章说 需要 设置-DLUAC_COMPATIBLE_FORMAT=ON重新编译。不过这个方案没有跑通，这问题有什么简单的解决方法没。

**Comment by chexiongsheng** [comment]
google 一下 unexpected symbol near '<\239>
