### ISSUE TITLE
求助  webgl平台 没有集成lua-protobuf吗  

### ISSUE THREAD

**Issue by Lang-Ren-01** [chexiongsheng/build_xlua_with_libs#52]
我尝试把 pb.c添加到 xlua_webgl.cpp中 build工程，但是会报各种错误。大佬有时间 支持一下webgl平台吗，我出微信小游戏包，lua pb 解析不了
![image](https://github.com/chexiongsheng/build_xlua_with_libs/assets/87970158/767d0395-a9b8-47ca-9ecd-860d4dabeb5c)

**Comment by chexiongsheng** [comment]
放到这个目录：https://github.com/chexiongsheng/build_xlua_with_libs/tree/master/LibsTestProj/WebGLPlugins
参考下rapidjson：https://github.com/chexiongsheng/build_xlua_with_libs/blob/master/LibsTestProj/Assets/Plugins/WebGL/rapidjson_webgl.cpp

你测试OK可以提交个PR过来
