### ISSUE TITLE
对于在lua-protobuf使用中，xlua从byte[]自动转成string，导致pb解析失败

### ISSUE THREAD

**Issue by yang1339** [chexiongsheng/build_xlua_with_libs#54]
大部分消息是没问题的，少量消息，尤其是带有中文时，经常出现问题
会报错：un-finished bytes (len 42 at offset 21)，有些人遇到解决了，但是方案都不是很明确
哪位大佬能给个解决方案吗？

就算用base64处理后在lua中解出来，但是只要在lua里面传值，还是会转成string，并没有解决问题

有哪位大佬解决过这个问题~

**Comment by chexiongsheng** [comment]
byte[]自动转lua string不会导致你说的问题。lua的string就是一段buffer+一个长度，恰好和byte[]一模一样，能完整承载所有信息。

你说的问题应该是你用的lua-protobuf没处理好（中文），去lua-protobuf那确认有没有这样的问题，怎么修复。

问的地方就不对，难怪处理不好。

**Comment by yang1339** [comment]
https://github.com/starwing/lua-protobuf/issues/133
是遇到了这个问题，确实看起来是中文导致的问题，但是这个在byte[]转string的时候，应该是编码导致的问题，这看起来是lua语言的问题，他出问题是在lua-protobuf解析前出了问题

**Comment by chexiongsheng** [comment]
刚刚特意看了lua的代码，就一个按长度memcpy，没编码。lua被人吐槽的一点是字符串编码支持不好，utf8的编码还要另外调用库。
另外，你仔细看你发的那个issue，最终结论不是用户自己编码了吗？和lua有啥关系？

**Comment by yang1339** [comment]
这个问题有点迷，绝大部分是好的，确实在涉及中文时，转化就可能出现异常，等我再跟深入去跟一下具体的自己再给出问题吧。谢谢大佬的关注。

**Comment by chexiongsheng** [comment]
这问题不迷，是你迷。
你跑过来怀疑的点，通过看lua相关源码只需要一分钟就能确认了。你发个你觉得和你同问题的issue，连issue结论都没搞明白。
按这些看，你自己写错代码的概率比底层出错的概率大几万倍吧。
