### ISSUE TITLE
你好，pbc和打包以后遇见一个问题

### ISSUE THREAD

**Issue by fyj2015** [chexiongsheng/build_xlua_with_libs#6]
问题是这样的：
我先用cmake打出一个build64，里面包含了pbc，然后我按照你的例子去调用luaopen_protobuf_c，他就报错说是找不到这个入口。请问我该怎么办

**Comment by fyj2015** [comment]
EntryPointNotFoundException: luaopen_protobuf_c

**Comment by fyj2015** [comment]
你好这个问题解决了。但是现在开始崩溃。。一起动就崩溃。。。

**Comment by chexiongsheng** [comment]
直接用现成的：https://github.com/chexiongsheng/build_xlua_with_libs

你自己编译的，只能说是哪个环节编出问题了，需要自行定位。

**Comment by fyj2015** [comment]
谢谢，能把你编译的工程发出来吗。我现在报个错，但是我不知道哪里的问题。想调试看看。但是自己编译的还崩溃

**Comment by fyj2015** [comment]
LuaException: lua/protobuf.lua:505: register fail
stack traceback:
	[C]: in function 'protobuf.c._env_register'
	lua/protobuf.lua:505: in function 'lua/protobuf.register_file'
	[string "chunk"]:33: in global 'read'
	[string "chunk"]:24: in global 'main'
	[string "chunk"]:39: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:429)
XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:262)
LuaComponet.ExcuteScript (System.String scriptName) (at Assets/Script/module/middlemodule/LuaComponet.cs:29)
Main.Start () (at Assets/Script/main/Main.cs:23)
用了你的dll以后报这个错

**Comment by chexiongsheng** [comment]
其它人用都是好的，只能说是你的用法问题。
我只是编译了pbc，具体这个库的使用自己查阅资料或者问相关人。
