### ISSUE TITLE
可以集成云风的sproto进来么？

### ISSUE THREAD

**Issue by 8liang** [chexiongsheng/build_xlua_with_libs#8]
可以集成云风的sproto进来么？我尝试集成，可能是方法不对，没法用，会报错EntryPointNotFoundException: luaopen_sproto_core

**Comment by chexiongsheng** [comment]
参照文档和这里集成的几个项目来做。
很多项目都会有其特殊要求的库，要都集成，不说其它的，光包大小估计你就接受不了。

**Comment by 8liang** [comment]
已经解决了，感谢你的启发
